"""Reproducible reporting helpers."""

from __future__ import annotations

from .analysis import RichClubResult


def methods_paragraph(result: RichClubResult) -> str:
    """Generate editable Methods text from the exact analysis settings."""

    p = result.parameters
    coefficient = (
        "an Opsahl-style weighted rich-club coefficient"
        if p["weighted"]
        else "the binary rich-club coefficient"
    )
    caveat = (
        " For weighted analyses, null networks also preserved the global edge-weight "
        "distribution by random permutation."
        if p["weighted"]
        else ""
    )
    return (
        f"Rich-club organization was evaluated across {p['richness']} thresholds using "
        f"{coefficient}. The observed network was compared with {p['n_random']} null "
        f"networks generated by degree-preserving double-edge swaps "
        f"({p['swaps_per_edge']} attempted swaps per edge; random seed {p['seed']})."
        f"{caveat} Normalized coefficients were calculated as the observed coefficient "
        "divided by the mean null coefficient. Empirical one-sided p-values used a "
        "plus-one correction. Thresholds retaining fewer than "
        f"{p['min_rich_nodes']} rich nodes were flagged as unstable and excluded from "
        "signal designation. Analyses were performed with RichClub Explorer v0.1.0."
    )
